"""adding image column

Revision ID: ee95215595ee
Revises: 23256b53b38c
Create Date: 2021-10-14 14:44:58.215595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee95215595ee'
down_revision = '23256b53b38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('image_url', sa.String(length=2000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'image_url')
    # ### end Alembic commands ###
