"""fixed nullable primary keys

Revision ID: db448d1cfce2
Revises: 8fac3f120a30
Create Date: 2021-10-08 13:39:01.333554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db448d1cfce2'
down_revision = '8fac3f120a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'run_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'run_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
