"""empty message

Revision ID: 6b13e4d5d8b9
Revises: 23256b53b38c
Create Date: 2021-10-14 14:31:22.891756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b13e4d5d8b9'
down_revision = '23256b53b38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('image_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'image_url')
    # ### end Alembic commands ###
