"""update users table to have weight age and height

Revision ID: 3af04cad7fff
Revises: ffdc0a98111c
Create Date: 2021-10-08 10:03:52.472876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af04cad7fff'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('height', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('weight', sa.Integer(), nullable=False))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weight')
    op.drop_column('users', 'height')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
